version: '3.8'

volumes:
  db_store:

services:
  api:
    image: node:16.2.0-alpine3.11
    container_name: api_node
    env_file: ./api/.env
    volumes:
      - ./api:/api
    ports:
      - '3000:3000'
    working_dir: /api
    stdin_open: true
    tty: true
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=api:*

    depends_on: 
      - db
    command: npm start
  db:
    image: mysql:8.0
    env_file: ./db/.env
    container_name: db_mysql
    volumes:
      - db_store:/var/lib/mysql
      - ./db/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./db/init_db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
